module(
    name = "monorepo",
    version = "latest",
)

# Bazel stuff
bazel_dep(name = "bazel_skylib", version = "1.9.2")
bazel_dep(name = "bazelrc-preset.bzl", version = "1.9.2")
bazel_dep(name = "platforms", version = "1.1.0")
bazel_dep(name = "rules_shell", version = "0.8.0")

# TODO(hermetic-llvm): https://github.com/hermeticbuild/hermetic-llvm/issues/221
# bazel_dep(name = "llvm", version = "0.8.19")
# toolchain = use_extension("@llvm//extensions:toolchain.bzl", "toolchain")
# toolchain.exec(arch = "x86_64", os = "linux")
# toolchain.target(arch = "x86_64", os = "linux")
# use_repo(toolchain, "llvm_toolchains")
# register_toolchains("@llvm//toolchain:all")
# llvm = use_extension("@llvm//extensions:llvm.bzl", "llvm")
# llvm.version(llvm_version = "23.1.0")

# LLVM
bazel_dep(name = "toolchains_llvm")
git_override(
    module_name = "toolchains_llvm",
    commit = "2711d4189ff8c5670ecd1df46bbb1e758073fe78",
    remote = "https://github.com/bazel-contrib/toolchains_llvm",
)

# Configure and register the toolchain.
llvm = use_extension("@toolchains_llvm//toolchain/extensions:llvm.bzl", "llvm")
llvm.toolchain(
    link_flags = {"": ["--ld-path=/home/linuxbrew/.linuxbrew/bin/wild"]},
    llvm_version = "23.1.0",
)
use_repo(llvm, "llvm_toolchain", "llvm_toolchain_llvm")

register_toolchains("@llvm_toolchain//:all")

# C++ std module
std_module = use_extension("//bazel:std_module.bzl", "std_module")
use_repo(std_module, "std_module")

# C++ stuff
bazel_dep(name = "abseil-cpp", version = "20260817.0")
bazel_dep(name = "boost", version = "1.90.0.bcr.2")
bazel_dep(name = "catch2", version = "3.15.1")
bazel_dep(name = "cpptrace", version = "1.0.4.bcr.1")
bazel_dep(name = "google_benchmark", version = "1.9.5")
bazel_dep(name = "magic_enum", version = "0.9.8")
bazel_dep(name = "quill", version = "13.0.0")
bazel_dep(name = "rules_cc", version = "0.2.22")

# Compile commands
# TODO: this thing is pretty bad, maybe https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2024/p2977r1.html is the fix
bazel_dep(name = "hedron_compile_commands", dev_dependency = True)
git_override(
    module_name = "hedron_compile_commands",
    commit = "513b4b589e05779debeb7d35d96b74efb2c94b96",
    remote = "https://github.com/rdong8/bazel-compile-commands-extractor",
)

# Docs
bazel_dep(name = "rules_doxygen", version = "2.6.4", dev_dependency = True)
git_override(
    module_name = "rules_doxygen",
    commit = "0b74d0a622c8fa625da9435eef34a0a564f77569",
    remote = "https://github.com/rdong8/rules_doxygen",
)

doxygen_extension = use_extension("@rules_doxygen//:extensions.bzl", "doxygen_extension")
use_repo(doxygen_extension, "doxygen")

http_archive = use_repo_rule("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")
http_archive(
    name = "doxygen_awesome_css",
    urls = ["https://github.com/jothepro/doxygen-awesome-css/archive/refs/tags/v2.4.2.tar.gz"],
    sha256 = "6f527e5733723bfd7243c28f24588dca4714cf977fea6147fdb4ae2050244409",
    strip_prefix = "doxygen-awesome-css-2.4.2",
    build_file_content = """
exports_files(["doxygen-awesome.css"])

filegroup(
    name = "css",
    srcs = ["doxygen-awesome.css"],
    visibility = ["//visibility:public"],
)
""",
)

