FROM docker.io/fedora:latest

RUN \
  dnf update -y \
  && dnf install -y \
    @development-tools \
    curl \
    clang \
    clang-tools-extra-devel \
    cmake \
    compiler-rt \
    file \
    fish \
    libcxx-devel \
    lldb \
    llvm \
    ninja-build \
    procps-ng \
    which \
  && dnf clean all && rm -rf /var/cache/dnf

ARG USERNAME=dev
RUN useradd -ms /usr/bin/bash $USERNAME

USER $USERNAME

ENV EDITOR=code
