# Credit: https://github.com/cpp-best-practices/cmake_template/blob/main/cmake/CompilerWarnings.cmake
# https://best.openssf.org/Compiler-Hardening-Guides/Compiler-Options-Hardening-Guide-for-C-and-C++.html

set(CMAKE_COMPILE_WARNING_AS_ERROR ON)
set(CMAKE_LINK_WARNING_AS_ERROR ON)

function(set_compile_warnings config)
    # TODO: https://gitlab.kitware.com/cmake/cmake/-/work_items/27783
    # Globally suppress warning for standard library module targets generated by CMake
    add_compile_options("$<$<CXX_COMPILER_ID:Clang>:-Wno-reserved-module-identifier>")

    set(CLANG_WARNINGS
    )

    set(GCC_WARNINGS
        "-Wduplicated-branches" # Warn if if / else branches have duplicated code
        "-Wduplicated-cond" # Warn if if / else chain has duplicated conditions
        "-Wlogical-op" # Warn about logical operations being used where bitwise were probably wanted
        "-Wmisleading-indentation" # Warn if indentation implies blocks where blocks do not exist
        "-Wsuggest-override" # Warn if an overridden member function is not marked 'override' or 'final'
        "-Wuseless-cast" # Warn if you perform a cast to the same type
    )

    target_compile_options("${config}"
        INTERFACE
            "$<$<CXX_COMPILER_ID:Clang>:${CLANG_WARNINGS}>"
            "$<$<CXX_COMPILER_ID:GCC>:${GCC_WARNINGS}>"
            "-Wall"
            "-Wcast-align" # Warn for potential performance problem casts
            "-Wconversion" # Warn on type conversions that may lose data
            "-Wdouble-promotion" # Warn if float is implicit promoted to double
            "-Wextra" # Reasonable and standard
            "-Wformat=2" # Warn on security issues around functions that format output (ie printf)
            "-Wimplicit-fallthrough" # Warn on statements that fallthrough without an explicit annotation
            "-Wnon-virtual-dtor" # Warn the user if a class with virtual functions has a non-virtual destructor. This helps catch hard to track down memory errors
            "-Wnull-dereference" # Warn if a null dereference is detected
            "-Wold-style-cast" # Warn for c-style casts
            "-Woverloaded-virtual" # Warn if you overload (not override) a virtual function
            "-Wpedantic" # Warn if non-standard C++ is used
            "-Wunused" # Warn on anything being unused
    )
endfunction()
