# TODO: ideally this is placed llvm-project/ itself but not sure how to have it tracked by the root project's git but not the subproject

config-mlir:
    cmake \
        -S llvm-project/llvm \
        -B llvm-project/build \
        -G Ninja \
        -DCMAKE_BUILD_TYPE='Debug' \
        -DCMAKE_C_COMPILER='clang' \
        -DCMAKE_CXX_COMPILER='clang++' \
        -DLLVM_BUILD_EXAMPLES='ON' \
        -DLLVM_CCACHE_BUILD='ON' \
        -DLLVM_ENABLE_ASSERTIONS='ON' \
        -DLLVM_ENABLE_PROJECTS='mlir' \
        -DLLVM_OPTIMIZED_TABLEGEN='ON' \
        -DLLVM_TARGETS_TO_BUILD='Native' \
        -DLLVM_USE_LINKER='mold' \
        -DLLVM_USE_SPLIT_DWARF='ON' \
        -DMLIR_INCLUDE_INTEGRATION_TESTS='ON'

build-mlir:
    cmake \
        --build llvm-project/build \
        --target check-mlir

install-llvm-pre-push:
    mkdir -p ../.git/modules/submodules/llvm-project/hooks/pre-push
    ln -sf llvm-project/llvm/utils/git/pre-push.py ../.git/modules/submodules/llvm-project/hooks/pre-push

check-llvm:
    cd llvm-project && git clang-format HEAD~1
